### ISSUE TITLE
Appreciate the wiki!

### ISSUE THREAD

**Issue by CeranPaul** [adtrevor/SwiftGeometryHelper#1]
Most people don't use that tool to explain their code.  I also liked how thorough you were in showing the possible cases in your routine for intersecting two circles.  The one comment in French threw me.  

My repository CeranPaul/SketchCurves does similar functions.  You might find it useful.  It's easy to ignore the Z coordinate, or k component if working in the XY plane.

**Comment by adtrevor** [comment]
And I appreciate your contribution to this project!
I'll fix the comment soon and I'll take a look at your repository.
I saw that you are also making a math repository. In my opinion it would be definitely great if we could make a single Swift repository for math/geometry where many people could contribute.

**Comment by adtrevor** [comment]
Especially since Swift is now open source and available on Linux, because such projects would be great for platforms like Raspberry Pi,  at the time I made this project, I was making human robot project for high school, the robot arm was controlled from an OS X app that included this code, it was useful for basic IK. If Swift was available on Linux at this time, it would have opened a whole new world of possibilities.

**Comment by CeranPaul** [comment]
I had not realized going open source meant that Swift could be run on an R Pi.  Thank you for waking me up!

My motivation for geometry code in Swift is to make simple parts for a 3D printer.  A diverse set of needs will make for stronger code!
